<?xml version="1.0" encoding="ISO-8859-1" standalone="yes"?>

<!DOCTYPE mesh [
	<!ELEMENT mesh       (polygons)>
	<!ELEMENT polygons   (polygon+)>
	<!ELEMENT polygon    (vertex+)>
	<!ELEMENT vertex     (skin+)>

	<!ELEMENT skin        EMPTY>

	<!ATTLIST vertex x CDATA #REQUIRED>
	<!ATTLIST vertex y CDATA #REQUIRED>
	<!ATTLIST vertex z CDATA #REQUIRED>
	<!ATTLIST vertex r CDATA #REQUIRED>
	<!ATTLIST vertex g CDATA #REQUIRED>
	<!ATTLIST vertex b CDATA #REQUIRED>
	<!ATTLIST vertex a CDATA #REQUIRED>
	<!ATTLIST vertex nx CDATA #REQUIRED>
	<!ATTLIST vertex ny CDATA #REQUIRED>
	<!ATTLIST vertex nz CDATA #REQUIRED>
	<!ATTLIST vertex u CDATA #REQUIRED>
	<!ATTLIST vertex v CDATA #REQUIRED>
	<!ATTLIST skin bone CDATA #REQUIRED>
	<!ATTLIST skin weight CDATA #REQUIRED>
]>

<mesh>
	<polygons>
		<polygon>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.698517" y="0.708319" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.692652" ny="0.699706" nz="-0.175054"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.723232" y="0.732893" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.692752" ny="0.719939" nz="-0.0422231"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.723232" y="0.732893" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.692752" ny="0.719939" nz="-0.0422231"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.399462" y="0.935555" z="13.2058"
				r="1" g="1" b="1" a="1"
				nx="-0.37019" ny="0.927998" nz="-0.0421755"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.399462" y="0.935555" z="13.2058"
				r="1" g="1" b="1" a="1"
				nx="-0.37019" ny="0.927998" nz="-0.0421755"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.399462" y="0.935555" z="13.2058"
				r="1" g="1" b="1" a="1"
				nx="-0.37019" ny="0.927998" nz="-0.0421755"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.011836" y="1.00358" z="13.1413"
				r="1" g="1" b="1" a="1"
				nx="-0.00730862" ny="0.999109" nz="-0.0415683"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.011836" y="1.00358" z="13.1413"
				r="1" g="1" b="1" a="1"
				nx="-0.00730862" ny="0.999109" nz="-0.0415683"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.011836" y="1.00358" z="13.1413"
				r="1" g="1" b="1" a="1"
				nx="-0.00730862" ny="0.999109" nz="-0.0415683"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.424015" y="0.930735" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.352145" ny="0.935165" nz="-0.038207"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.424015" y="0.930735" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.352145" ny="0.935165" nz="-0.038207"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.424015" y="0.930735" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.352145" ny="0.935165" nz="-0.038207"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.755863" y="0.735086" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.729793" ny="0.682678" nz="-0.0367772"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.893759" y="0.37247" z="12.3795"
				r="1" g="1" b="1" a="1"
				nx="0.921287" ny="0.351105" nz="-0.167198"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.916923" y="0.386946" z="13.1556"
				r="1" g="1" b="1" a="1"
				nx="0.934078" ny="0.355535" nz="-0.0330737"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.755863" y="0.735086" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.729793" ny="0.682678" nz="-0.0367772"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.916923" y="0.386946" z="13.1556"
				r="1" g="1" b="1" a="1"
				nx="0.934078" ny="0.355535" nz="-0.0330737"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.997131" y="0.0308189" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.982225" ny="0.0895922" nz="-0.164946"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.893759" y="0.37247" z="12.3795"
				r="1" g="1" b="1" a="1"
				nx="0.921287" ny="0.351105" nz="-0.167198"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.916923" y="0.386946" z="13.1556"
				r="1" g="1" b="1" a="1"
				nx="0.934078" ny="0.355535" nz="-0.0330737"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.916923" y="0.386946" z="13.1556"
				r="1" g="1" b="1" a="1"
				nx="0.934078" ny="0.355535" nz="-0.0330737"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="1.0234" y="0.0350208" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.996258" ny="0.0802145" nz="-0.0321849"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.997131" y="0.0308189" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.982225" ny="0.0895922" nz="-0.164946"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.950936" y="-0.380505" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.923557" ny="-0.350883" nz="-0.15467"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.997131" y="0.0308189" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.982225" ny="0.0895922" nz="-0.164946"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.97582" y="-0.388671" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.931962" ny="-0.361165" nz="-0.0317337"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="1.0234" y="0.0350208" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.996258" ny="0.0802145" nz="-0.0321849"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.97582" y="-0.388671" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.931962" ny="-0.361165" nz="-0.0317337"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.997131" y="0.0308189" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.982225" ny="0.0895922" nz="-0.164946"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.36868" y="-0.899705" z="12.379"
				r="1" g="1" b="1" a="1"
				nx="0.320159" ny="-0.93737" nz="-0.13724"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.722202" y="-0.695457" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.664895" ny="-0.734558" nz="-0.13542"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.740208" y="-0.713094" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.683101" ny="-0.729635" nz="-0.0317166"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.740208" y="-0.713094" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.683101" ny="-0.729635" nz="-0.0317166"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.376056" y="-0.923483" z="13.1068"
				r="1" g="1" b="1" a="1"
				nx="0.326138" ny="-0.944755" nz="-0.0327491"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.36868" y="-0.899705" z="12.379"
				r="1" g="1" b="1" a="1"
				nx="0.320159" ny="-0.93737" nz="-0.13724"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.00432573" y="-0.95249" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.0112253" ny="-0.989525" nz="-0.143927"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.36868" y="-0.899705" z="12.379"
				r="1" g="1" b="1" a="1"
				nx="0.320159" ny="-0.93737" nz="-0.13724"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.376056" y="-0.923483" z="13.1068"
				r="1" g="1" b="1" a="1"
				nx="0.326138" ny="-0.944755" nz="-0.0327491"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.376056" y="-0.923483" z="13.1068"
				r="1" g="1" b="1" a="1"
				nx="0.326138" ny="-0.944755" nz="-0.0327491"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00816635" y="-0.977856" z="13.2023"
				r="1" g="1" b="1" a="1"
				nx="-0.0277999" ny="-0.999135" nz="-0.0309246"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00432573" y="-0.95249" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.0112253" ny="-0.989525" nz="-0.143927"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.365825" y="-0.893201" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.339584" ny="-0.929094" nz="-0.146517"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00432573" y="-0.95249" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.0112253" ny="-0.989525" nz="-0.143927"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00816635" y="-0.977856" z="13.2023"
				r="1" g="1" b="1" a="1"
				nx="-0.0277999" ny="-0.999135" nz="-0.0309246"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.00816635" y="-0.977856" z="13.2023"
				r="1" g="1" b="1" a="1"
				nx="-0.0277999" ny="-0.999135" nz="-0.0309246"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.380536" y="-0.916783" z="13.204"
				r="1" g="1" b="1" a="1"
				nx="-0.330362" ny="-0.943281" nz="-0.0328942"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.365825" y="-0.893201" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.339584" ny="-0.929094" nz="-0.146517"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.728867" y="-0.708699" z="13.1283"
				r="1" g="1" b="1" a="1"
				nx="-0.701488" ny="-0.711699" nz="-0.0373939"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.365825" y="-0.893201" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.339584" ny="-0.929094" nz="-0.146517"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.380536" y="-0.916783" z="13.204"
				r="1" g="1" b="1" a="1"
				nx="-0.330362" ny="-0.943281" nz="-0.0328942"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.365825" y="-0.893201" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.339584" ny="-0.929094" nz="-0.146517"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.728867" y="-0.708699" z="13.1283"
				r="1" g="1" b="1" a="1"
				nx="-0.701488" ny="-0.711699" nz="-0.0373939"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.703987" y="-0.691192" z="12.3792"
				r="1" g="1" b="1" a="1"
				nx="-0.693696" ny="-0.703508" nz="-0.154476"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.916867" y="-0.34739" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.92158" ny="-0.354541" nz="-0.158084"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.703987" y="-0.691192" z="12.3792"
				r="1" g="1" b="1" a="1"
				nx="-0.693696" ny="-0.703508" nz="-0.154476"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.728867" y="-0.708699" z="13.1283"
				r="1" g="1" b="1" a="1"
				nx="-0.701488" ny="-0.711699" nz="-0.0373939"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.728867" y="-0.708699" z="13.1283"
				r="1" g="1" b="1" a="1"
				nx="-0.701488" ny="-0.711699" nz="-0.0373939"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.948147" y="-0.354561" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.937346" ny="-0.346254" nz="-0.0386088"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.916867" y="-0.34739" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.92158" ny="-0.354541" nz="-0.158084"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.981105" y="-0.00161934" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.986541" ny="0.000668249" nz="-0.163514"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.916867" y="-0.34739" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.92158" ny="-0.354541" nz="-0.158084"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.948147" y="-0.354561" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.937346" ny="-0.346254" nz="-0.0386088"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.948147" y="-0.354561" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.937346" ny="-0.346254" nz="-0.0386088"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.01432" y="0.00160789" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.999099" ny="-0.0134825" nz="-0.0402297"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.981105" y="-0.00161934" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.986541" ny="0.000668249" nz="-0.163514"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.942584" y="0.386935" z="13.1355"
				r="1" g="1" b="1" a="1"
				nx="-0.929894" ny="0.365348" nz="-0.0426376"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.981105" y="-0.00161934" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.986541" ny="0.000668249" nz="-0.163514"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-1.01432" y="0.00160789" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.999099" ny="-0.0134825" nz="-0.0402297"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.981105" y="-0.00161934" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.986541" ny="0.000668249" nz="-0.163514"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.942584" y="0.386935" z="13.1355"
				r="1" g="1" b="1" a="1"
				nx="-0.929894" ny="0.365348" nz="-0.0426376"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.911466" y="0.37246" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.916469" ny="0.361879" nz="-0.170668"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.698517" y="0.708319" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.692652" ny="0.699706" nz="-0.175054"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.911466" y="0.37246" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.916469" ny="0.361879" nz="-0.170668"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.942584" y="0.386935" z="13.1355"
				r="1" g="1" b="1" a="1"
				nx="-0.929894" ny="0.365348" nz="-0.0426376"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.942584" y="0.386935" z="13.1355"
				r="1" g="1" b="1" a="1"
				nx="-0.929894" ny="0.365348" nz="-0.0426376"
				u="0.505257" v="0.988863">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.723232" y="0.732893" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="-0.692752" ny="0.719939" nz="-0.0422231"
				u="0.444993" v="0.988848">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.698517" y="0.708319" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.692652" ny="0.699706" nz="-0.175054"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.722202" y="-0.695457" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.664895" ny="-0.734558" nz="-0.13542"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.950936" y="-0.380505" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.923557" ny="-0.350883" nz="-0.15467"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.97582" y="-0.388671" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.931962" ny="-0.361165" nz="-0.0317337"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.97582" y="-0.388671" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.931962" ny="-0.361165" nz="-0.0317337"
				u="0.567306" v="0.988859">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.740208" y="-0.713094" z="13.2037"
				r="1" g="1" b="1" a="1"
				nx="0.683101" ny="-0.729635" nz="-0.0317166"
				u="0.50592" v="0.988847">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.722202" y="-0.695457" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.664895" ny="-0.734558" nz="-0.13542"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.274687" y="0.612525" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="-0.346328" ny="0.903343" nz="-0.253037"
				u="0.505355" v="0.688935">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.496868" y="0.473452" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="-0.683814" ny="0.685022" nz="-0.251284"
				u="0.567635" v="0.688897">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.698517" y="0.708319" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.692652" ny="0.699706" nz="-0.175054"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.698517" y="0.708319" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.692652" ny="0.699706" nz="-0.175054"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.274687" y="0.612525" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="-0.346328" ny="0.903343" nz="-0.253037"
				u="0.505355" v="0.688935">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.00868423" y="0.659208" z="11.4322"
				r="1" g="1" b="1" a="1"
				nx="-0.0526589" ny="0.966203" nz="-0.252348"
				u="0.444935" v="0.688918">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.274687" y="0.612525" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="-0.346328" ny="0.903343" nz="-0.253037"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.384199" y="0.905064" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="-0.352516" ny="0.919133" nz="-0.175862"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00868423" y="0.659208" z="11.4322"
				r="1" g="1" b="1" a="1"
				nx="-0.0526589" ny="0.966203" nz="-0.252348"
				u="0.444935" v="0.688918">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.308279" y="0.637891" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.352347" ny="0.901117" nz="-0.252666"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00868423" y="0.659208" z="11.4322"
				r="1" g="1" b="1" a="1"
				nx="-0.0526589" ny="0.966203" nz="-0.252348"
				u="0.567635" v="0.688897">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="-0.00788827" y="0.971106" z="12.3793"
				r="1" g="1" b="1" a="1"
				nx="-0.00852893" ny="0.985307" nz="-0.170579"
				u="0.567236" v="0.853473">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.308279" y="0.637891" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.352347" ny="0.901117" nz="-0.252666"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.518137" y="0.474957" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.754139" ny="0.608469" nz="-0.247063"
				u="0.505355" v="0.688935">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.308279" y="0.637891" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.352347" ny="0.901117" nz="-0.252666"
				u="0.444935" v="0.688918">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.415239" y="0.900385" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.3429" ny="0.924149" nz="-0.16843"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.505269" v="0.853776">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.518137" y="0.474957" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.754139" ny="0.608469" nz="-0.247063"
				u="0.505355" v="0.688935">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.628662" y="0.236051" z="11.4323"
				r="1" g="1" b="1" a="1"
				nx="0.907602" ny="0.345231" nz="-0.238904"
				u="0.444935" v="0.688918">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.518137" y="0.474957" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.754139" ny="0.608469" nz="-0.247063"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.893759" y="0.37247" z="12.3795"
				r="1" g="1" b="1" a="1"
				nx="0.921287" ny="0.351105" nz="-0.167198"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.7374" y="0.710447" z="12.38"
				r="1" g="1" b="1" a="1"
				nx="0.728479" ny="0.662022" nz="-0.176197"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.893759" y="0.37247" z="12.3795"
				r="1" g="1" b="1" a="1"
				nx="0.921287" ny="0.351105" nz="-0.167198"
				u="0.444988" v="0.853611">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.518137" y="0.474957" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.754139" ny="0.608469" nz="-0.247063"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
		</polygon>
		<polygon>
			<vertex x="0.701733" y="-0.00545216" z="11.4327"
				r="1" g="1" b="1" a="1"
				nx="0.966546" ny="0.0879094" nz="-0.24096"
				u="0.567635" v="0.688897">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.628662" y="0.236051" z="11.4323"
				r="1" g="1" b="1" a="1"
				nx="0.907602" ny="0.345231" nz="-0.238904"
				u="0.505816" v="0.688896">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>
			<vertex x="0.893759" y="0.37247" z="12.3795"
				r="1" g="1" b="1" a="1"
				nx="0.921287" ny="0.351105" nz="-0.167198"
				u="0.50584" v="0.853466">
					<skin bone="dummy_bone" weight="1"/>
			</vertex>